name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies and build
        run: |
          npm install
          npm run build-only
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "leonardo.rock22@hotmail.com"
          git config --global user.name "Leonardo Soares"
          cd dist
          git init
          git add .
          git commit -m "Deploy"
          git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" master:gh-pages
